### ISSUE TITLE
On Packet Event cancels certain packets

### ISSUE THREAD

**Issue by boomertink123** [Anarchick/skript-packet#12]
The on packet event, when used with the packet 'play_server_spawn_entity' will automatically cancel packets coming from the server if the entity being spawned is an item.

Steps to Reproduce
|> Install latest versions of Skript, Skript-packet, and ProtocolLib
|> Include the line 'on packet event play_server_spawn_entity:'
|> drop/spawn/do anything that would send an entity spawn packet for an item from the server

Expected Behavior
The event gets called and the packet isn't affected

Video of the issue:
https://user-images.githubusercontent.com/76920120/182928647-0da58c8d-00fb-44fc-b725-d5276bd57bcb.mp4

Server Information
Server version/platform: Paper 1.17.1
Skript version: 2.6.3

Other Details
Of all the packet events I've tested so far, this is the only case where a packet gets affected by having an event for it

**Comment by Anarchick** [comment]
Hi, did you try to sync the event ?
`on sync packet event play_server_spawn_entity:`

**Comment by boomertink123** [comment]
It works now, thanks!
