### ISSUE TITLE
Hey thanks for your engagement to bring updates for TPA but I sadly have one problem:

### ISSUE THREAD

**Issue by Oktobi** [Anarchick/skript-packet#13]

**Comment by Oktobi** [comment]
I use Java 16 so I can't use the plugin. Could you add support for Java 16 please?
`fr/anarchick/skriptpacket/SkriptPacket has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0`

**Comment by Anarchick** [comment]
This as been discuss in private, and sorry, but i will not downgrade the compiler version.
Java 17 is an LTS (Long Term Support) where Java 16 is not.

The user (=you), should use Java 17 instead of Java 16
