### ISSUE TITLE
problem when editing the particle's type in `play_server_world_particles` packet

### ISSUE THREAD

**Issue by AKtomik** [Anarchick/skript-packet#15]
Hi !
I use the `play_server_world_particles` packet to show particle to a player.
But when i'd like to change the type of the particle by modifying the field 9 with the id of particle desired (id find [here](https://wiki.vg/Protocol#Particle)), the execution of the skript **brutally stop**, whithout error when load or when executed.
code part : 
```
    set {_packet} to new play_server_world_particles packet
    broadcast "how"
    set field 9 of {_packet} to 6
    broadcast "that work ?"
```
execution :
![javaw_yiFZ0A7D1k](https://user-images.githubusercontent.com/97125853/198428757-b5bc9ead-7531-4b98-96ed-6b039ef4045f.png)

using the particle name does not work and send error saying 'use number' :
![javaw_KsJNskMMHg](https://user-images.githubusercontent.com/97125853/198428796-edc66824-d087-457d-9e0f-305b14d6786b.png)

so, how you change the particle type in a `play_server_world_particles` packet correctly ?
Else, is it a bug ?
Thank you in advance for your help !

**Comment by Anarchick** [comment]
I don't know why you need to create this packet. Skript already does client side particles

**Comment by AKtomik** [comment]
I would like to use this method to show custom particles to the player because:
- With packet, its most customizable.
- With packet, you can "store" the particule effect and just send it wen you need it
Got a better sollution ?

**Comment by AKtomik** [comment]
so, you dont have any solution to use this packet ?

**Comment by Anarchick** [comment]
Assuming mc1.19.3, The field 9 of play_server_world_particles is not a number but an NMS object.
as said here : https://www.spigotmc.org/threads/protocollib-particles.436986/ , you should use native Skript or addon to do that
