### ISSUE TITLE
Reloading skript with packet event duplicates event

### ISSUE THREAD

**Issue by boxic** [Anarchick/skript-packet#16]
Like the title suggests, every time I reload a skript with this event, it triggers another time, increasing by 1 every reload until I restart the server.

```
# When player closes out of a sign gui, updating it and sending a packet
on packet event play_client_update_sign:

	# Get location of sign
	set {_location} to location field 0 of event-packet
	
	# No actual sign there, it was a fake GUI sign
	block at {_location} is not a sign
	
	# Get line text of sign
	set {_lines::*} to field 1 of event-packet

	# Trigger GUI sign closing event
	guis_sign_closed(event-player, {_lines::*})
```

![image](https://user-images.githubusercontent.com/6758224/199842010-3a5f1490-3f40-4af2-9392-4ac9c882785d.png)

Server version is paper 1.19.2 on a velocity proxy

Skript addons:
![image](https://user-images.githubusercontent.com/6758224/199842425-2e7692c0-45ae-4515-b425-4d8d7ca462b3.png)

Plugin list:
![image](https://user-images.githubusercontent.com/6758224/199842458-f4bb6415-43f9-4ad1-af83-9ae591198a31.png)

**Comment by Binjabin** [comment]
I also get this exact same issue.

**Comment by Anarchick** [comment]
I was able to replicate and solve it !
Fix in next update :)
