### ISSUE TITLE
give a list of all packet name

### ISSUE THREAD

**Issue by AKtomik** [Anarchick/skript-packet#17]
Hi !
Could you give a list of all packets which give for each packet :
- the name of packet in Wiki.vg
- the name of packet in skript-packet
- _more ?_

Because, when we want to find the script-packet name of a packet we found in Wiki.vg, it can be long and trouble.
(for exemple, i find this packet https://wiki.vg/Protocol#Player_Info_Update and i'd like to use it, but I can not find his skript-packet name)

Thank you in advance, and thank to you for your beautiful work on this useful addon !

**Comment by Anarchick** [comment]
Hi, SP use ProtocolLib and his own packets names.
I'm not abble to give you the equivalent of wiki.vg <-> ProtocolLib.

You can use the first function here to search a packet by name : [https://github.com/Anarchick/skript-packet/wiki/Packets-Listening](https://github.com/Anarchick/skript-packet/wiki/Packets-Listening)

**Comment by AKtomik** [comment]
Before, I was using the `searchpacket` method but now i discovered a javadoc page, its make the same things but in a web page :)
(https://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/PacketType.Play.Client.html)

But which is hard, its the equivalent of wiki.vg <-> ProtocolLib... (sometimes, names are realy different !)
Anyhow, thanks for your help ! If anyone has the equivalent of wiki.vg <-> ProtocolLib, please, send it ! (i close issue?)
