### ISSUE TITLE
"`PLAYER_SERVER_PLAYER_INFO` is not supported by your server", are you sure ?

### ISSUE THREAD

**Issue by AKtomik** [Anarchick/skript-packet#18]
_Id like to use tablist packets with skript-packet_

When i try to use the packet `PLAYER_SERVER_PLAYER_INFO`, i get an error saying 
`PLAYER_SERVER_PLAYER_INFO` is not supported by your server
![image](https://user-images.githubusercontent.com/97125853/212573662-d23da7fc-ad8f-450a-99c2-f5c54c170b76.png)
so far no problem

But the packet `PLAYER_SERVER_PLAYER_INFO` allow the server to update player's info in the tab (user list). (information from [here](https://wiki.vg/Protocol#Player_Info_Update))
So, how the server update and manage the tablist list if he dont use the `PLAYER_SERVER_PLAYER_INFO` packet ?
- he use another similar packet ? **No**, acording to [wiki.vg](https://wiki.vg/Protocol), `PLAYER_SERVER_PLAYER_INFO` is the only way to update tablist (with `PLAYER_SERVER_PLAYER_INFO_REMOVE`, but we have another problem with he)
- **skript-packet say wrong ?** Probably not, but possible (you to confirm)
- **i miss something ?** Totaly possible.

Im on the last version of paper 1.19.3, using the last version of skript and the last version of skript-packet.
The `PLAYER_SERVER_PLAYER_INFO` packet type is repertoried [here](https://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/PacketType.Play.Server.html#PLAYER_INFO) (screen down there) and in `all packettypes` skript-packet expression
![image](https://user-images.githubusercontent.com/97125853/212574834-8ffac885-e3b7-449a-8a76-e34a15ae9864.png)

This issue is the result of the truble of an entier day : Now im locked here, and i dont understand how is it possible that "`PLAYER_SERVER_PLAYER_INFO` is not supported by your server".
Take this issue as a questionnement, because im not sure, and I probably miss somethings.
(and i created the issue #17 due to this truble)

**Comment by Anarchick** [comment]
can't replicate. works fine for me mc1.19.3, protocollib v5.0.0-snapshot.

```
on packet event play_server_player_info:
    set {packet} to event-packet
    broadcast {packet}
```

**Comment by AKtomik** [comment]
ok !
Problem patch when updating ProtocolLib from v5.0.0-SNAPSHOT-b600 to v5.0.0-SNAPSHOT-b612.
(before)
![image](https://user-images.githubusercontent.com/97125853/215170288-2bb1cd35-6cd7-41a2-bd18-1276c3f48c62.png)
(after)
![image](https://user-images.githubusercontent.com/97125853/215174633-7e543964-dceb-4d10-8053-287e8953863a.png)
So, now its working !

I was locked for 2 weeks about that, the solution was just to update protocolib, so dumb. 
It a mistake from me. moral: **update protocolLib to the latest version**

Thank for your help, and thank for skript-packet !!
