### ISSUE TITLE
Send Packet syntax not supported on 1.19.2 (I believe)

### ISSUE THREAD

**Issue by FardSniffer** [Anarchick/skript-packet#19]
When trying to send packets, console always outputs an error (I have tried also using an actual packet too):
![image](https://user-images.githubusercontent.com/62638217/214378965-ffb111df-996f-4775-89f6-8aa93f299adb.png)

This is quite unfortunate, however, this is probably not surprising as it's 1.19.2, I haven't tested this on 1.18.2 though.
I'm using skript-packet 2.1.

(Error: https://pastebin.com/VR0evWb2)
Thanks :)

**Comment by Anarchick** [comment]
SP works fine in 1.19.3 with ProtocolLib v5.0.0-SNAPSHOT-b608
