### ISSUE TITLE
Fix UTF-8 Character

### ISSUE THREAD

**Issue by cooffeeRequired** [Anarchick/skript-packet#21]
Error occured before the fix
![image](https://user-images.githubusercontent.com/106232282/222446491-db31b8c7-5fa8-44b9-8e57-38702cccb8fc.png)

**Added this to gradle.build file** `compileJava.options.encoding = 'UTF-8'`
Fixed version
.
.
[skript-packet-main-2.1.1.zip](https://github.com/Anarchick/skript-packet/files/10871963/skript-packet-main-2.1.1.zip)

**Comment by cooffeeRequired** [comment]
**Tested on 1.19.3**

**Comment by ExtraSmartMiner** [comment]
thanks works on 1.19.2

**Comment by boxic** [comment]
worked, thanks <3

**Comment by boxic** [comment]
works on 1.19.4

**Comment by Anarchick** [comment]
Official fix with 2.1.2
