### ISSUE TITLE
"pattern compiling exception" and many errors in console (1.19.4)

### ISSUE THREAD

**Issue by HC-Emro** [Anarchick/skript-packet#22]
I know Protocollib is still in dev release for 1.19.4 with regular additions. I just updated it just now and I still have the incompatibility with skript-packet which disables all my skripts and spams the console on startup.
I don't know if it comes from Skript-packet or from protocolib:

Here are the errors:
https://hastebin.com/share/japovehexu.yaml

Im on papermc 1.19.4 with last skript packet version and #635dev 1.19.4 protocollib.

**Comment by Anarchick** [comment]
Did you try #21 hotfix ?

**Comment by HC-Emro** [comment]
Yep I didn't see it, it works now. Thanks !
