### ISSUE TITLE
Handshake event not letting me in.

### ISSUE THREAD

**Issue by CerialPvP** [Anarchick/skript-packet#26]
Hello.
I have registered a handshake packet event, and when I did, that made me unable to join my server.
Code (I also tried broadcast):
```applescript
on packet event handshake_client_set_protocol:
    set {-ProtocolVersionHandshake} to field 0
```
There are no errors in the code, but this is what happens when I try to join:
![image](https://github.com/Anarchick/skript-packet/assets/71380797/968b754f-cb1c-4899-8338-9c489c11a5c2)
There are also no errors in console, and this is my /sk info:
![image](https://github.com/Anarchick/skript-packet/assets/71380797/3c5c3335-dfd6-4ba6-979e-af7b3b8e6e57)
I have protocollib v5.1.0 build #661, as seen here:
![image](https://github.com/Anarchick/skript-packet/assets/71380797/f4f1db63-4798-4c06-b85a-bf09e97ec06a)
Please fix or help me asap.

**Comment by Anarchick** [comment]
I have updated SP and cannot replicate this issue
