### ISSUE TITLE
field location error

### ISSUE THREAD

**Issue by gagore** [Anarchick/skript-packet#28]
Server Version: git-Paper-292 (MC: 1.20.2)
Skript Version: 2.6.4
Installed Skript Addons:
 - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
 - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
 - SkQuery v4.1.10
 - SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee)
 - Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet)
Installed dependencies:
 - Vault v1.7.3-b131
 - WorldGuard v7.0.9+5934e49
 
 ProtocolLib v5.1.0

Outputs the player's coordinates instead of the block's coordinates

code:
```
on packet event play_client_update_sign:
	broadcast "<pink>%all fields of event-packet%"
	set {_location} to location field 0 of event-packet
	broadcast {_location}
```
	
debug:
```
[19:48:55 INFO]: BlockPosition{x=-64, y=44, z=69}, [aaea1, , , ] and false
[19:48:55 INFO]: x: -66.83, y: 45, z: 69.47, yaw: -92.65, pitch: 37.65 in 'world'
```

**Comment by Anarchick** [comment]
Field 0 refer to an nms object, you have to get the bukkit object first.

Location of (wrap from nms (field 0))
