### ISSUE TITLE
Plugin doesn't work on 1.20.4

### ISSUE THREAD

**Issue by JakeGBLP** [Anarchick/skript-packet#29]
Using Protocollib's latest build with skript-packet on 1.20.4 doesn't work, i can't tell whether it's protocollib's fault or skript-packet's, but here i am, opening an issue about it just in case. (No errors are sent but packet events arent fired)

**Comment by Anarchick** [comment]
Hi, I'm in a long time vacation without my computer. The update will take some Times. (No estimation). Any java dev Can fork thé project to make a patch 😉

**Comment by JakeGBLP** [comment]
well rip idk how to do that

**Comment by DelayedGaming** [comment]
Done some testing, ProtocolLib is not updated to run on 1.20.4, so there's nothing we can do until it is solved to cross out any potential issues in skript-packet loading.

**Comment by Anarchick** [comment]
Someone also Said that skript-packet does not works with 1.20.1, it's true ?

**Comment by jacklollz2** [comment]
I don't think it's working. I have the latest version of ProtocolLib and my scripts are not functioning.

**Comment by Vulcano771** [comment]
So I run 1.20.4 and it works for me

**Comment by JakeGBLP** [comment]
Idk what happened, it works, i have no idea what errors came up before because it wasn't me that had them, i guess it works!
