### ISSUE TITLE
Skript-Packet 2.2.0 Bug

### ISSUE THREAD

**Issue by TSNCM** [Anarchick/skript-packet#31]
Hello, I have a vehicle system with the on packet event PLAY_CLIENT_STEER_VEHICLE. 
As soon as I reload my vehicle system with /sk reload Vehicle and then drive, everything is faster. 
The steering is twice as fast. When I reload the vehicle system again, the steering and the W S A D keys are even faster. 
I had this problem before with the script packet. 

I suspect that there's a bug in the packet.

Minecraft-Server-Version: 1.20.2 ( paper )

**Comment by Anarchick** [comment]
try to listen the packet without doing anything inside the event.
try same with : `on sync packet event PLAY_CLIENT_STEER_VEHICLE`
then `on async packet event PLAY_CLIENT_STEER_VEHICLE`

**Comment by TSNCM** [comment]
Hello, I have the latest version of ProtocolLib, and I'm still experiencing the bug.

**Comment by Anarchick** [comment]
Can you send the code please, I will try to reproduce the bug

**Comment by TSNCM** [comment]
I am using: Skript-Reflect, Skbee, Skript, Skript-Packet
You can Spawn Vehicle with command: /cartest 1
You can delete Vehicle Variable with command: /cartest 2
You can drive with W, S, A, D
`import:
	io.papermc.paper.entity.TeleportFlag$EntityState
	org.bukkit.event.vehicle.VehicleEntityCollisionEvent as Collide

on load:
	delete {DrivingCars::*}

on packet event PLAY_CLIENT_STEER_VEHICLE:
	set {_LeftRight} to field 0 of event-packet
	set {_Forward} to field 1 of event-packet
	set {_Jump} to field 2 of event-packet
	set {_Exit} to field 3 of event-packet
	set {_Kmh} to {Car::KMH::%uuid of player%}

# When pressed A.
	if {_LeftRight} is bigger than 0:
		if name of vehicle of player is "d-seat":
			set {_Rotation} to metadata tag "Vehicle.Rotation" of player
			remove 4 from {_Rotation}
			set metadata tag "Vehicle.Rotation" of player to {_Rotation}

# When pressed D.
	if {_LeftRight} is less than 0:
		if name of vehicle of player is "d-seat":
			set {_Rotation} to metadata tag "Vehicle.Rotation" of player
			add 4 to {_Rotation}
			set metadata tag "Vehicle.Rotation" of player to {_Rotation}
# When pressed W.
	if {_Forward} is bigger than 0:
		if name of vehicle of player is "d-seat":
			if {_Kmh} is less than 100:
				add 0.5 to {_Kmh}
				set {Car::KMH::%uuid of player%} to {_Kmh}
# When pressed S.
	if {_Forward} is less than 0:
		if name of vehicle of player is "d-seat":
			if {_Kmh} is more than 0:
				remove 1.5 from {_Kmh}
				set {Car::KMH::%uuid of player%} to {_Kmh}
				if {_Kmh} < 0:
					set {Car::KMH::%uuid of player%} to 0
	if {_Exit} is true:
		set {Car::KMH::%{Car::UUID::%{uuid::car::%player's vehicle's uuid%}%::1}%} to 0
		delete {driver::%{uuid::car::%uuid of vehicle of player%}%}

command /cartest [<integer>]:
	trigger:
		if arg-1 is 2:
			delete {DrivingCars::*}
			stop
		delete {DrivingCars::*}
		set {carspawnfix::%player's uuid%} to player's location
		set pitch of {carspawnfix::%player's uuid%} to 0
		teleport player to {carspawnfix::%player's uuid%}
		set {_Lead} to nbt compound from "{Rotation:[%player's yaw%f],CustomNameVisible:0b,NoGravity:1b,FallFlying:0b,OnGround:1b,Small:0b,Silent:1b,NoAI:1b,NoBasePlate:0b,ShowArms:0b,Invisible:0b,Invulnerable:1b,PersistenceRequired:1,DisabledSlots:2039583}"
		spawn armor stand at player's location with nbt {_Lead}
		set {_lead} to last spawned armor stand
		set {Car::UUID::%arg-1%::1} to last spawned entity
		set {uuid::car::%last spawned entity's uuid%} to arg-1
		set {Car::spawn::%arg-1%::2} to location 0.4 behind and 0.4 meter left {Car::UUID::%arg-1%::1}
		set {Car::spawn::%arg-1%::3} to location 0.4 behind and 0.4 meter right {Car::UUID::%arg-1%::1}
		set {Car::spawn::%arg-1%::4} to location 0.4 forward and 0.4 meter left {Car::UUID::%arg-1%::1}
		set {Car::spawn::%arg-1%::5} to location 0.4 forward and 0.4 meter right {Car::UUID::%arg-1%::1}

		remove 0.2 from y coord of {Car::spawn::%arg-1%::2}
		remove 0.2 from y coord of {Car::spawn::%arg-1%::3}
		remove 0.2 from y coord of {Car::spawn::%arg-1%::4}
		remove 0.2 from y coord of {Car::spawn::%arg-1%::5}

		set {carspawn%player's uuid%} to 1
		loop 4 times:
			add 1 to {carspawn%player's uuid%}
			set {_Seat} to nbt compound from "{Rotation:[%player's yaw%f],CustomNameVisible:1b,FallFlying:0b,OnGround:0b,Small:1b,Silent:1b,NoAI:1b,NoBasePlate:1b,ShowArms:0b,Invisible:0b,Invulnerable:1b,PersistenceRequired:1,DisabledSlots:2039583}"
			spawn armor stand at {Car::spawn::%arg-1%::%{carspawn%player's uuid%}%} with nbt {_Seat}
			if {carspawn%player's uuid%} is 4:
				set name of last spawned entity to "d-seat"
				set gravity of last spawned entity to false
			else:
				set name of last spawned entity to "p-seat"
				set gravity of last spawned entity to false
			set {uuid::car::%last spawned entity's uuid%} to arg-1
			set {Car::UUID::%arg-1%::%{carspawn%player's uuid%}%} to last spawned entity


on rightclick on armor stand:
	if name of clicked entity is "d-seat" or "p-seat":
		make player ride clicked entity
	if name of clicked entity is "d-seat":
		set {driver::%{uuid::car::%player's vehicle's uuid%}%} to player
		remove "%{uuid::car::%player's vehicle's uuid%}%" from {DrivingCars::*}
		add "%{uuid::car::%player's vehicle's uuid%}%" to {DrivingCars::*}
	set {Car::KMH::%uuid of player%} to 0
	set metadata tag "Vehicle.Rotation" of player to yaw of vehicle of player


every 1 tick:
	loop {DrivingCars::*}:
		set {_Kmh} to {Car::KMH::%uuid of {driver::%loop-value%}%} * 1.5
		set {_Kmh} to round({_Kmh})
		if {Tank::%loop-value%} is not set:
			set {Tank::%loop-value%} to 0
		if metadata tag "Vehicle.Rotation" of {driver::%loop-value%} is not set:
			set {_Rotation} to yaw of {Car::UUID::%loop-value%::1}
		else:
			set {_Rotation} to metadata tag "Vehicle.Rotation" of {driver::%loop-value%}
		send action bar "&bPing: &b%ping of {driver::%loop-value%}% &f%{_Kmh}% Km/h" to {driver::%loop-value%}
		set {_Kmh} to {Car::KMH::%uuid of {driver::%loop-value%}%} / 100
		add nbt compound from "{Rotation:[%{_Rotation}%f]}" to nbt compound of {Car::UUID::%loop-value%::1}
# Model Rotation
		if {driver::%loop-value%} is set:
			set gravity of {Car::UUID::%loop-value%::1} to true
		else:
			set gravity of {Car::UUID::%loop-value%::1} to false
# KMH Calculation
		if {Car::UUID::%loop-value%::1} is not on ground:
			set {_half} to {_Kmh} / 4
		else:
			set {_half} to {_Kmh}

# Move System
		set gravity of {Car::UUID::%loop-value%::1} to true
		push {Car::UUID::%loop-value%::1} in direction of {Car::UUID::%loop-value%::1} at speed {_half}
		moveParts(loop-value)
		if {driver::%loop-value%}'s vehicle is armor stand:
			if name of {driver::%loop-value%}'s vehicle is "d-seat":
				set {nixmoruk} to "nix"
			else:
				delete {driver::%loop-value%}
				set {Car::KMH::%uuid of {Car::UUID::%loop-value%::1}%} to 0
		else:
			delete {driver::%loop-value%}
			set {Car::KMH::%uuid of {Car::UUID::%loop-value%::1}%} to 0

function moveParts(id: text):
	set {Car::spawn::%{_id}%::2} to location 0.4 behind and 0.4 meter left {Car::UUID::%{_id}%::1}
	set {Car::spawn::%{_id}%::3} to location 0.4 behind and 0.4 meter right {Car::UUID::%{_id}%::1}
	set {Car::spawn::%{_id}%::4} to location 0.4 forward and 0.4 meter left {Car::UUID::%{_id}%::1}
	set {Car::spawn::%{_id}%::5} to location 0.4 forward and 0.4 meter right {Car::UUID::%{_id}%::1}

	remove 0.2 from y coord of {Car::spawn::%{_id}%::2}
	remove 0.2 from y coord of {Car::spawn::%{_id}%::3}
	remove 0.2 from y coord of {Car::spawn::%{_id}%::4}
	remove 0.2 from y coord of {Car::spawn::%{_id}%::5}

	set {_Drive} to 1
	loop 5 times:
		add 1 to {_Drive}
		{Car::UUID::%{_id}%::%{_Drive}%}.teleport({Car::spawn::%{_id}%::%{_Drive}%}, EntityState.RETAIN_PASSENGERS)`
