### ISSUE TITLE
Event Duplication of effects after reload

### ISSUE THREAD

**Issue by MovesLikeJaeger** [Anarchick/skript-packet#32]
After reloading a script, events effects will trigger (the amount of times you have reloaded the script +1) every time a single event fires - only on packet events

Here is a basic example:
`on packet play_client_chat:`
`  send "a" to console`

![image](https://github.com/Anarchick/skript-packet/assets/75779721/c8f1b57f-c4ae-4e4b-a923-2fc985a210c1)

As you can see, the "a" sends multiple times even though it should only be sending once, and it sends an extra time every script reload that happens.
I have been able to replicate this on multiple if not all packet events and it is happening on both 1.20.X and 1.19.X
This is happening on the ProtocolLib artifact you suggested to use rather than the latest official release, but it also happens on that release too.
Skript 2.8.4
Paper 1.19.4 - 1.20.4 (Both versions tested)
Skript-Reflect (2.4 /or 2.4 nightly build to fix custom events) was active during this test

Thanks for reading,
Jaeger.

**Comment by Anarchick** [comment]
Hi, can you try with this version and tell me if the issue is solved. Thx.
[Skript-Packet-2.2.1.zip](https://github.com/Anarchick/skript-packet/files/15143518/Skript-Packet-2.2.1.zip)

**Comment by MovesLikeJaeger** [comment]
> Hi, can you try with this version and tell me if the issue is solved. Thx. [Skript-Packet-2.2.1.zip](https://github.com/Anarchick/skript-packet/files/15143518/Skript-Packet-2.2.1.zip)

Amazing! That fixed the problem.

Really appreciate the hasty reply and solution. Thank you on behalf of the Skript community, and for keeping this addon up to date.

Much love.
