### ISSUE TITLE
The syntaxes stop working when we reload a .sk file

### ISSUE THREAD

**Issue by HC-Emro** [Anarchick/skript-packet#8]
When I reload a skript that doesn't contain skript-packet stuff, other scripts that have skript-packet syntaxes stop working.

You can try it by creating 2 .sk files.
In the first script, you put skript-packet stuff like:

on packet event play_client_STEER_VEHICLE:
  send "test" to player

In the second one, you put another random stuff like:

on chat:
  send "test2" to player

Now, restart the server. Trigger the first event by mounting an entity (like armor stand), it should work. After that, reload the second script, and retry to trigger the first event, it will not work.

Skript 2.6, Skript-packet 2.0.1 on Paper 399 (1.17.1)

My addons:
![image](https://user-images.githubusercontent.com/56135028/146680913-35e11f59-23f5-4729-9e3e-e79404bdf3d8.png)

**Comment by Anarchick** [comment]
Already Fixed for the next release. Can you try this non official release and tell me if it solve the issue ?
[skript-packet-2.1.0.jar.zip](https://github.com/Anarchick/skript-packet/files/7741365/skript-packet-2.1.0.jar.zip)

**Comment by HC-Emro** [comment]
It's working, thanks :)
