### ISSUE TITLE
Skript 2.6.2 not work

### ISSUE THREAD

**Issue by ZConnorZ** [Anarchick/skript-packet#9]
Hi, the Skript has been updated [2.6.2]. Unfortunately, Skript-packed does not run on the new version. Since there are changes in the loading of addons.

**Comment by Anarchick** [comment]
[skript-packet-2.1.0-BETA.jar.zip](https://github.com/Anarchick/skript-packet/files/8750281/skript-packet-2.1.0-BETA.jar.zip)

Hi, I made this hotfix. Does it works ? (Note : YOU HAVE TO USE JAVA 17+ even if you're not using a recent version of Minecraft)

**Comment by ZConnorZ** [comment]
Hi, plugin is working now :)

**Comment by Anarchick** [comment]
Official release is available. It's not like this beta file so you should replace it :)
